# Generated by Django 4.1.4 on 2024-02-05 22:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hotel_gile.main_app.functions.auxiliary_func
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Запитване',
                'verbose_name_plural': '2. Запитвания',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Качи снимка')),
            ],
            options={
                'verbose_name': 'Галерия',
                'verbose_name_plural': '3. Галерия',
            },
        ),
        migrations.CreateModel(
            name='HeroGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Качи снимка')),
            ],
            options={
                'verbose_name': 'Начална Галерия',
                'verbose_name_plural': '5. Начална Галерия',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Резервация №')),
                ('status', models.CharField(choices=[('0', 'Заявена'), ('1', 'Потвърдена'), ('2', 'Платена през Booking'), ('3', 'Платена')], default='0', max_length=1, verbose_name='Статус')),
                ('added_on', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Резервирана на')),
                ('external_id', models.CharField(blank=True, max_length=32, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('locker_password_id', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='Имена')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон за връзка')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Имейл')),
                ('generate_password', models.BooleanField(default=False, verbose_name='Генерирай парола за достъп')),
                ('check_in', models.DateTimeField(default=hotel_gile.main_app.functions.auxiliary_func.default_check_in, help_text='Ако няма час на пристигане остави 14:00', verbose_name='Настаняване')),
                ('check_out', models.DateTimeField(default=hotel_gile.main_app.functions.auxiliary_func.default_check_out, verbose_name='Напускане')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Коментар')),
            ],
            options={
                'verbose_name': 'Резервация',
                'verbose_name_plural': '1. Резервации',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Име')),
                ('pros', models.TextField(verbose_name='Предимства')),
                ('cons', models.TextField(blank=True, null=True, verbose_name='Недостатъци')),
                ('score', models.FloatField(max_length=5, verbose_name='Оценка')),
                ('date', models.DateTimeField(verbose_name='Дата на отзива')),
                ('check_in', models.DateField(verbose_name='Настанен')),
                ('check_out', models.DateField(verbose_name='Напуснал')),
                ('room', models.CharField(max_length=30, verbose_name='Стая')),
            ],
            options={
                'verbose_name': 'Отзив',
                'verbose_name_plural': '7. Отзиви',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='№ стая')),
                ('room_title', models.CharField(max_length=100, verbose_name='Име на стая')),
                ('room_title_en', models.CharField(help_text='На английски', max_length=100, verbose_name='Name of room')),
                ('room_capacity', models.IntegerField(help_text='Максимален брой гости', verbose_name='Капацитет')),
                ('room_size', models.IntegerField(help_text='м3', verbose_name='Квадратура')),
                ('room_services', models.TextField(verbose_name='Екстри')),
                ('room_services_en', models.TextField(help_text='На английски', verbose_name='Services')),
                ('image', models.ImageField(upload_to='room/', verbose_name='Качи снимка')),
            ],
            options={
                'verbose_name': 'Стая',
                'verbose_name_plural': '4. Стаи',
            },
        ),
        migrations.CreateModel(
            name='TermWorkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('bg', 'Български')], max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Термини',
                'verbose_name_plural': '6. Термини',
            },
        ),
        migrations.CreateModel(
            name='TermWorkListCol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_ident', models.CharField(db_index=True, max_length=50, verbose_name='Идентификат')),
                ('column_description', models.TextField(blank=True, verbose_name='Съдържание')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.termworklist')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRoomPrice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('persons', models.IntegerField(blank=True)),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main_app.room')),
            ],
            options={
                'verbose_name': 'historical Цена',
                'verbose_name_plural': 'historical Ценоразпис',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ArchivedReservation',
            fields=[
            ],
            options={
                'verbose_name': 'Архивирана резервация',
                'verbose_name_plural': '8. Архивирани резервации',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.reservation',),
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.IntegerField(blank=True)),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.room')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Ценоразпис',
                'unique_together': {('id', 'room', 'persons')},
            },
        ),
        migrations.CreateModel(
            name='ReservedRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveIntegerField(default=0, verbose_name='Брой възрастни')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='Брой деца')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='Отстъпка/ Надценка')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Цена')),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.reservation')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.room', verbose_name='Стая')),
            ],
            options={
                'verbose_name': 'стая',
                'verbose_name_plural': 'стаи',
                'unique_together': {('reservation', 'room')},
            },
        ),
    ]
