# Generated by Django 4.2.10 on 2024-08-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_paymentlogs_reservation_payment_counter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentlogs',
            options={'verbose_name': 'Банков лог', 'verbose_name_plural': '9. Банкови логове'},
        ),
        migrations.AlterField(
            model_name='paymentlogs',
            name='request_body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentlogs',
            name='response_body',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
