# Generated by Django 4.2.10 on 2024-08-31 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_paymentlogs_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='payment_url',
        ),
    ]
