# Generated by Django 4.1.3 on 2023-01-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_reservation_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='test',
        ),
    ]
